### ISSUE TITLE
Unable to select adress in Altena / scroll to Altena on map

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#108]
**Describe the bug**
In the backoffice (https://signalen.s-hertogenbosch.dev/incident/beschrijf) it is not possible to create a signal in de municipality of Altena, e.g. adres Bellefleur 1 Andel. 

**Expected behavior**
Because the customer service of Afvalstoffendienst is going to register signals, they must be able to create a signal in the municipality of Altena in the backoffice of Signalen

**Comment by boris-arkenaar** [comment]
fixed by adding Altena to the list of municipalities for 's-Hertogenbosch.
