### ISSUE TITLE
Accessibility: [SIG-3302] Unknown address for screen readers

### ISSUE THREAD

**Issue by aditudorache** [Signalen/frontend#110]
**Description**
Gebruikers kunnen een locatie op de kaart aangeven, dat kan overeen komen met een adres maar ook zonder adres, bijvoorbeeld in een park. Voor gebruikers met een visuele beperking is dit niet mogelijk. er kan via het veld alleen een bestaand adres worden ingevuld.

**Acceptance criterium**
Tekst toevoegen alleen voor screen readers met de tekst “Weet u het adres niet, bel dan 14020 om telefonisch de melding te maken.”

Tekst in aria-label zetten op de kaart

**Comment by someren** [comment]
De tekst die getoond wordt moet door functioneel beheer aanpasbaar zijn. Het telefoonnummer 14020 wordt gebruikt door Amsterdam, niet door 's-Hertogenbosch.
