### ISSUE TITLE
Filter "Afdeling" does not work correctly for categories with one Afdeling

### ISSUE THREAD

**Issue by someren** [Signalen/frontend#124]
**Describe the bug**
A user working for department WXL created a filter: Toegewezen aan: j.doesburg@s-hertogenbosch.nl + categorie = Graffiti & Beplakking. He then added Afdeling = WXL and signal 2020 dissapeared from the list.

Since categorie Graffiti & Beplakking has only one department, this is rather strange. It should not have dissapeared from the results.
I have looked at all signals and concluded the following: only signal 2020 (the one that dissapears) was entered in Signalen with categorie "overig". It was manually corrected to "Graffiti & Beplakking". All other signals got the categorie "Graffiti & Beplakking" from the start. The routing expression makes sure that these signals are directly assigned to department WXL.

**To Reproduce**
1. Go to 'Filter'
2. Create the following filter: Toegewezen aan = j.doesburg@s-hertogenbosch.nl + categorie = Graffiti & Beplakking
3. Click "Filteren"
4. Check the list and see if signal 2020 is present
5. Click on "Filteren" and add Afdeling = Weener XL
6. Click on "Filteren" and check if signal 2020 is still present (it probably dissapeared).

**Expected behavior**
Since categorie Graffity & Beplakking only has one department, it should not matter if the filter Afdeling is added or not. The signal should always be shown when categorie "Graffity & Beplakking" is selected.

**Screenshots**
![signalen 2020](https://user-images.githubusercontent.com/66589775/111154271-55235e00-8593-11eb-9a88-edd0e84e0c46.png)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser Chrome

**Comment by CBuiVNG** [comment]
Saving assigned to email does not seem to work properly.
I'm not seeing the assigned_user_email being sent in the patch. When I create the PATCH manually, it get stored in the back-end.
But when retrieving that filter, the assigned_user_email field is not pre-filled in the UI.

This also explains the behaviour described in the bug report, we are actually only filtering on the department.

**Comment by CBuiVNG** [comment]
Regarding the filter on assigned department:
there are 2 flows where we can get an association between department and signal
1) implicit via category
2) explicitly assigned via routing

You are filtering category (using 1) and after step 5 you are using the routing department. These are 2 different flows.
When you filter via method 2, an assignment has to exist (via routing). For this testcase, that's not the case (only the implicit association is known), and the filter will yield empty.

I agree that this can be a bit confusing, and we might need to think of a way to make this more intuitive. For now this works as designed.

**Comment by someren** [comment]
Getest, speelt nog steeds.

**Comment by someren** [comment]
Correctie! Op accp hadden de melding geen afdeling. Probleem lijkt inmiddels opgelost. Story gesloten
