### ISSUE TITLE
Error message incorrect after uploading wrong format file

### ISSUE THREAD

**Issue by someren** [Signalen/frontend#126]
**Describe the bug**
The error message which is shown after uploading a wrong format file is very unclear:
1. The colour of the text is blue instead of red or similar to other warnings (red background, white letters). As a result I did not see the error message the first time and only noticed it wasn't attached at the summary.
2. The text is incorrect. It shows three available formats: .jpeg, .png and .gif. However, I am also able to upload .jpg files. This format should also be included in the error message.
3. Additional: Please check on file size as well (see #125) and show a warning on the same location.

**To Reproduce**
1. Go to 'Melden'
2. Click on 'Plus' at "Foto's toevoegen'
3. Choose a wrong file format like .pdf

**Expected behavior**
I expect a very clear warning or error message after uploading a wrong file format.
I expect a correct error message
I expect that it also checks on file size and not after submitting my signal

**Screenshots**

![image](https://user-images.githubusercontent.com/66589775/114136007-5766a700-990a-11eb-9700-7bfcdc4a67f6.png)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser Chrome

**Comment by someren** [comment]
Alternative: Increase the maximum upload size from 2/3 MB to 10-15MB. Pictures that are made on a smartphone are simply larger than a few MB...

**Comment by MauritsR** [comment]
I'm working on a fix for the first 2 issues. The 3rd point is discussed in https://github.com/Signalen/frontend/issues/125

**Comment by boris-arkenaar** [comment]
This seems to have been fixed now.
<img width="613" alt="Screenshot 2021-11-13 at 14 36 42" src="https://user-images.githubusercontent.com/2932084/141645910-65301579-47b4-41ba-9ed0-d2d128341fcc.png">
