### ISSUE TITLE
Button "Alles selecteren" and "Niets selecteren" doesn't work for categories

### ISSUE THREAD

**Issue by someren** [Signalen/frontend#127]
**Describe the bug**
When creating a filter in Signalen you can choose "Alles selecteren". This function still works with status, stadsdeel, bron and afdeling. However, it does not work with Categories any more. The buttons do not respond.

**To Reproduce**
1. Go to 'Afhandelen'
2. Click on 'Filteren'
3. Click on 'Alles selecteren'
4. Nothing happens
5. Select everything manually
6. Click on 'Niets selecteren'
7. Nothing happens

**Expected behavior**
After clicking "Alles selecteren" I expect every item to be selected.
After clicking "Niets selecteren" I expect every selected item to be deselected.

**Screenshots**
Alles selecteren
![image](https://user-images.githubusercontent.com/66589775/114522123-5653b380-9c43-11eb-9ec3-fd43b8ab4e66.png)

Niets selecteren:
![image](https://user-images.githubusercontent.com/66589775/114522047-4340e380-9c43-11eb-9514-7568fd6a7de1.png)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser Chrome
 - Version be 0.21.4, fe 1.44.0

**Additional context**
Please dubbelcheck why the automated testing did not find this bug.

**Comment by boris-arkenaar** [comment]
Fixed by Amsterdam
