### ISSUE TITLE
Manifest file not correctly rendered

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#147]
**Describe the bug**

Currently we seem to have two manifest files:

- /<hash>.json
- /manifest.json

The <hash>.json is referenced from the index.html but seems to contain only the template for the manifest without the variables substituted:

```
{
  "background_color": "$SIGNALS_BACKGROUND_COLOR",
  "display": "fullscreen",
  "icons": [
    {
      "src": "$SIGNALS_IOS_ICON",
      "sizes": "180x180",
      "type": "image/png"
    }
    ...
}
``` 

This results in an error in the browser:

![image](https://user-images.githubusercontent.com/5213690/118957297-b1727780-b960-11eb-96e2-29f5683d1d4b.png)

**To Reproduce**

1. Go to the latest production version (v1.48.0)
2. Launch the inspector
3. See the errors about the incorrect manifest properties

**Expected behavior**

The index.html should refer to a version of the manifest with replaced variables (e.g. /manifest.json).

**Comment by MauritsR** [comment]
Fixed in https://github.com/Amsterdam/signals-frontend/pull/1686 (released in v1.54.0) - can you re-test this and close if successful?
