### ISSUE TITLE
Add basic configuration abilities (logo, name, colours)

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#2]
**As a** system administrator
**I want** to be able to configure the frontend
**so** that I can tailor the application to our organization

We would like the application to be configurable with:

- A logo
- An organization name
- Primary colour
- Footer text
- Geolocation

**:wrench: Proposed technical solution**

- We configure these parameters using a JSON file that is mounted in the Docker container

**Comment by bartjkdp** [comment]
Originally from @boris-arkenaar 

We also want to have a neutral default styling then. One that is not Amsterdam specific.

**Comment by boris-arkenaar** [comment]
The app currently uses Amsterdam specific external libraries for fonts, icons, components, and themes [`amsterdam-styled-components`](https://github.com/Amsterdam/amsterdam-styled-components).

We want a custom default styling and then the possibility to configure some characteristics like the logo, color, title, etc.

I see two directions we could take.

1. Move away from `amsterdam-styled-components`.
2. Create a custom styling on top of `amsterdam-styled-components`.

Below I go into detail for each option and listing their pros and cons.

## Move away from `amsterdam-styled-components`

We have to remove the dependency on the Amsterdam components throughout the whole application and implement another component library (like [Material-UI](https://material-ui.com/)).

Then we can make some styling options configurable.

The Amsterdam instance of the app will, by far, not look and feel like the app currently does. How would Amsterdam feel about that?

### Pros

* Independent component library and styling.
* Freedom and flexibility for moving forward on our roadmap.

### Cons

* The whole application needs to be updated to use components from the new library.
* Amsterdam's instance doesn't look like an Amsterdam website anymore, as it does now.

## Create a custom styling on top of `amsterdam-styled-components`

Now we are explicitly bound to the Amsterdam component library, which could pose problems in the future, or sooner.

We can make some styling options configurable.

We could allow the Amsterdam instance to use their styling so their instance would look and feel exactly as it does now.

We could allow other instances to write a custom styling on top of the
component library as well if they'd like.

### Pros

* The application keeps using the components as it does now (no changes needed).
* Amsterdam's instance can keep it's current look and feel.

### Cons

* The application is tied to a component library specific to Amsterdam.
* We need to write a custom styling on top of the Amsterdam component library.
* We still need to think about a default set of icons and fonts as opposed to the ones Amsterdam is using now.

**Comment by aditudorache** [comment]
Hi Boris, please take into account in your analysis that the just released map component (amsterdam-react-maps) also has a amsterdam-styled-components package dependency.

**Comment by bartjkdp** [comment]
Maybe we can also leverage the work that is done at other places in VNG. Other Common Ground projects use the [Common Ground design system](https://commonground.gitlab.io/core/design-system/), a React / styled-components implementation of [NL Design System](https://designsystem.gebruikercentraal.nl/).

**Comment by jaccobrouwer** [comment]
Maybe we can set-up a short meeting with Tosh to exchange our thoughts and get some insights on their experience so far (?)

**Comment by bartjkdp** [comment]
From todays meeting: we should talk to the Dataportaal team of Amsterdam about themeability of [amsterdam-styled-components](https://github.com/Amsterdam/amsterdam-styled-components).
