### ISSUE TITLE
Re-open closed notifications

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#24]
Is it possible to re-open closed notifications? I used the admin account but apparently I have insuffient rights to re-open closed notifications?

**Comment by bartjkdp** [comment]
When you have administrator rights you can re-open a signal by changing the status: 

![image](https://user-images.githubusercontent.com/5213690/85008668-90f0da80-b15d-11ea-88de-c521c2b3d88c.png)

![image](https://user-images.githubusercontent.com/5213690/85008638-86364580-b15d-11ea-9e7f-ebd243504d90.png)

See for example: https://signalen.s-hertogenbosch.dev/manage/incident/39
