### ISSUE TITLE
Remove leaflet-headless dependency

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#3]
Original by @boris-arkenaar

~Or are we going to use something else than leaflet?~

**Comment by boris-arkenaar** [comment]
With that dependency out of the way:

- we can use the latest version of node;
- we have no dependencies anymore on the 'os libs' (`cairo`, `pango` and `cmake`).

**Comment by boris-arkenaar** [comment]
Turns out I can't just remove `leaflet-headless`. Unit tests won't run anymore.
It's going to take a lot more time to find a solution for this. So, for now I'd say: won't fix.
