### ISSUE TITLE
Search address still searches addresses in Amsterdam

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#36]
The search bar of the map displays streetnames of Amsterdam when you type in a search entry. It should display the street names of the municipality shown on the map. Also when typing in a postal code of 's-Hertogenbosch, no results are shown.

![image](https://user-images.githubusercontent.com/5213690/85009305-87b43d80-b15e-11ea-811e-4ad637b8c152.png)

**Comment by boris-arkenaar** [comment]
Made changes to the configuration. Lets check tomorrow if all is well!
