### ISSUE TITLE
Focus on error when a field it not filled in

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#37]
As a reporter I'm trying to create a notification. I accidentally forget to fill out a required field (or some other error occurs). I'm trying to get to the next step/page but nothing happens. 

When a reporter makes a mistake/gets an error could reporter be directed to the highlighted error?

**Comment by bartjkdp** [comment]
I agree, this would be much more user friendly. We can even just use native HTML5 for this.

**Comment by MauritsR** [comment]
Feature is available and the page will now scroll to the topmost error (see https://github.com/Amsterdam/signals-frontend/releases/tag/v1.46.0). @erikveerm Can the issue be closed?
