### ISSUE TITLE
Link in message after notification

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#38]
After submitting a notification you get a thank you message. Is it possible to add a link in this message so the user can immediately make another notification.

**Comment by MauritsR** [comment]
This was added with release https://github.com/Amsterdam/signals-frontend/releases/tag/v1.41.0. @erikveerm can this issue be closed?

**Comment by MauritsR** [comment]
![Screenshot 2021-05-05 at 14 23 37](https://user-images.githubusercontent.com/10672773/117140297-88bd8000-adad-11eb-90aa-3c07ae03e0a2.png)
