### ISSUE TITLE
Option earlier configurable?

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#39]
When choosing the option "earlier" in the webform, you can only choose dates up to one week ago. Is this configurable so we can choose period of time?

**Comment by bartjkdp** [comment]
This is currently hardcoded in the frontend here:

https://github.com/Signalen/frontend/blob/2e30e7cd9cc50fbe4134e8ceb574af6ae4dd62a2/src/signals/incident/components/form/DateTimeInput/index.js#L33-L37
