### ISSUE TITLE
Change description days to Dutch

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#42]
When choosing the option "earlier" in the webform, the days are stated in English instead of Dutch. Is this configurable so we can change the days into Dutch?

![image](https://user-images.githubusercontent.com/66015874/83971047-62f7d480-a8d9-11ea-99d5-97895668cb3d.png)

**Comment by bartjkdp** [comment]
This seems to be fixed now:

![image](https://user-images.githubusercontent.com/5213690/86108403-6723a600-bac3-11ea-944f-207d8ef4dbc1.png)
