### ISSUE TITLE
Adjustable time notifications shown on backoffice map

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#43]
The map option in the manage portal only shows notifications over the last 24 hours. Is this filter configurable and for example show all notifications over the previous week?

![image](https://user-images.githubusercontent.com/66015874/83971148-00530880-a8da-11ea-92fc-dd0619e7903a.png)

**Comment by bartjkdp** [comment]
This filter currently is hardcoded in the frontend code here: https://github.com/Signalen/frontend/blob/8b6be6be2a560c0723eebf87d45e161e02c4063a/src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js#L106-L113

The API supports generic requests for any time frame.
