### ISSUE TITLE
Taking big decisions and communicating breaking changes

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#47]
Two days ago a part of the team decided to drop IE11 support overnight (https://github.com/Amsterdam/signals-frontend/pull/929). We had a discussion on IE11 on May 7th in Slack and I recorded we decided to keep IE11 support for now, so at least for me this decision came as a surprise.

I think as we are going to support more and more municipalities with the Signalen codebase, we need to move towards a more careful approach of taking big (breaking) decisions. Also I think it is important to put a process in place of communicating breaking changes so users can take measures when updating Signalen.

What are your opinions on this? How can we find a way of offering stability to our users and at the same time keep improving Signalen?

**Comment by joostvkempen** [comment]
In general I think you should follow international and nationale laws, standards and guidelines. This may sound obvious, but is not common practice for most municipalities. They tend to have their own interpretation, or use them as minimum requirements and add rules of their own on top. One of the major goals and at the same time the major challenge of Samen Organiseren / Common Ground is to standardize between municipalities exactly on these kind of matters.

Concerning IE11, this is the applicable law: https://wetten.overheid.nl/BWBR0040936/2018-07-01. It states that every dutch government website (including all municipalities) should comply to EN 301 549, which includes WCAG2. It states that all mainstream user agents should be supported and this should be assessed on real usage. This makes this decision difficult: should we look at data from Amsterdam SIA? Or all websites of all municipalities? And over which period of time? And what is 'mainstream usage' ? 1%, 5% , 10% ??? Interesting fact: it is about real usage, so even when the browser is not officially supported anymore, when there's a significant amount of users, you should support it!

For now I would think these decisions should be made in a kind of decision board with a delegation of all participating municipalities. That's how it is done for OpenZaak. And later on maybe some issues can be dealt with by VNG-R on behalf of all municipalities. (Like supporting IE11 or not)

**Comment by bartjkdp** [comment]
We discussed this and created more awareness in the team on this topic.
