### ISSUE TITLE
Small map is not appearing in backoffice and submit page

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#50]
The backoffice does not show the small map of the location:

![image](https://user-images.githubusercontent.com/5213690/85007473-df9d7500-b15b-11ea-956f-7e99ac401ec4.png)

![Map Controleer uw gegevens](https://user-images.githubusercontent.com/66015874/83969898-dba76280-a8d2-11ea-9f94-45bf27845ffc.PNG)

**Link**
https://signalen.s-hertogenbosch.dev/manage/incident/39

**Comment by bartjkdp** [comment]
This appears to be fixed now.

**Comment by bartjkdp** [comment]
Whoops not really, for Utrecht it works, but for Den Bosch not.

**Comment by boris-arkenaar** [comment]
Seems like this might be a backend issue?
https://github.com/Amsterdam/signals-frontend/blob/cb09ec57a53f85bf0b09598efffa25111a965795/src/components/MapStatic/index.js#L86

Just came across this. Haven't done any extensive research.

**Comment by CBuiVNG** [comment]
I've debugged this issue and traced it back to the front-end requesting a map with lat, lon that are outside the amsterdam bbox.
We should not use the amsterdam mapserver for this purpose.

```
{"GET":{"scheme":"https","host":"map.data.amsterdam.nl","filename":"/maps/topografie","query":{"bbox":"147751.85958964945,411331.1204145328,148391.85958964945,411631.1204145328","format":"jpeg","height":"300","layers":"basiskaart","request":"getmap","srs":"EPSG:28992","version":"1.1.1","width":"640"},"remote":{"Address":"194.104.80.4:443"}}}
```
