### ISSUE TITLE
Help button redirects to a website hosted by Amsterdam

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#55]
The help button in the manage portal is redirecting to TamTam.amsterdam.nl. 
This should be configurable.  
In our case we would like to redirect to our IT-helpdesk: https://intraforms.s-hertogenbosch.nl/TriplEforms.aspx?scenario=scIC04

**Comment by boris-arkenaar** [comment]
@erikveerm That link does not seem to be working, unfortunately.

**Comment by erikveerm** [comment]
@boris-arkenaar This link is only accessible within our environment. It does work for me.
