### ISSUE TITLE
Summary page refers to Amsterdam

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#56]
After creating a new notification I get to the summary page. It now says: Ja, ik geef de gemeente Amsterdam toestemming om mijn contactgegevens te delen met andere organisaties, als dat nodig is om mijn melding goed op te lossen, see screenshot

![Checkbox](https://user-images.githubusercontent.com/66015874/85378569-046a6180-b53b-11ea-8a4a-7905217290a8.png)

**Comment by bartjkdp** [comment]
Duplicate of #58
