### ISSUE TITLE
Manifest.json does not work for some reason

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#57]
I am not sure why, but I am getting an error in the console:

![image](https://user-images.githubusercontent.com/5213690/85918439-17df3a80-b863-11ea-8409-7b908a17e2aa.png)

It seems that manifest.json cannot be found an the index.html is returned.

**Comment by bartjkdp** [comment]
Did some resource, indeed the commands:

```bash
envsubst < /usr/share/nginx/html/manifest.json > /tmp/manifest.json
mv /tmp/manifest.json /usr/share/nginx/html/manifest.json
```

in start.sh do not work as /usr/share/nginx/html/manifest.json does not exist.

**Comment by boris-arkenaar** [comment]
Fixed by https://github.com/Amsterdam/signals-frontend/pull/981
And locally will be fixed as well by https://github.com/Amsterdam/signals-frontend/pull/994
