### ISSUE TITLE
Zoom level map in backoffice

### ISSUE THREAD

**Issue by boris-arkenaar** [Signalen/frontend#60]
In the back-office the min, max, and initial zoom levels for the map are hard-coded.

https://github.com/Signalen/frontend/blob/abc62a4fc6091867c23c4befd483fdf4b628b201/src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js#L204-L206

These values are different from the ones configured in the config file, which are being used for the map in the incident form.

https://github.com/Signalen/frontend/blob/abc62a4fc6091867c23c4befd483fdf4b628b201/environment.conf.json#L68-L70

Do they need to be different?

We should make them configurable at least. So, we can make use of the existing configuration, or define different values for the back-office in the config file.

@janjaap

**Comment by janjaap** [comment]
The zoom levels differ because the map in the overview page needs to show the whole of the municipality in order to display all of the submitted incidents for the past 24 hours. The other maps serve a different purpose and thus have a zoom level that is different.
