### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BramVerbruggen** [Signalen/frontend#63]
In frontend, using Google-Chrome:
"Fout
Momenteel zijn er problemen met deze website en kan uw melding niet verwerkt worden.
Probeert u het later nogmaals.
Voor spoedeisende..."

-> nu ook in Edge dezelfde foutmeling (ook na verwijderen cookies/cache/geschiedenis).

**Comment by bartjkdp** [comment]
Duplicate of #41
