### ISSUE TITLE
Make map component reusable for other municipalities

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#7]
We would like to make the map component reusable for other municipalities. Geolocation is provided by the configuration in #2.

Possible solutions:
- NL Maps
- OpenStreetMap
- ?

@spreeker and @NieneB probably have good ideas about this.

**Comment by jaccobrouwer** [comment]
@bartjkdp and @boris-arkenaar can you both organize a brief meeeting with @spreeker to check on reuse-ability for Map components from the Energietransitie project

**Comment by bartjkdp** [comment]
The map now has maps of The Netherlands. We only need to make the geolocation and bounding box configurable.

**Comment by jaccobrouwer** [comment]
Ok, that's wonderful 👌

**Comment by BramVerbruggen** [comment]
NL Maps is a good option for orientation and geolocation on smaller scaling. Since NL Maps is like TOP10 a derivative of BGT you could consider using PDOK services for BGT to show up-to-date mapping in the largest scaling. Besides that, BGT contains more detailed objects, possibly needed later on for a signal a an asset (see user-story).

**Comment by jaccobrouwer** [comment]
@BramVerbruggen amstedam has based their 'new' maps on PDOK

**Comment by boris-arkenaar** [comment]
It looks like the map does not contain the whole of the Netherlands. Or do I need to 'unlock' it somehow?

**Comment by boris-arkenaar** [comment]
Connecting it with PDOK maps now. Amsterdam uses their own map tiles.
See #857

**Comment by spreeker** [comment]
We have out own maps available if needed. And possibility to style them for each municipality :)

**Comment by boris-arkenaar** [comment]
Sounds good! Where?
