### ISSUE TITLE
Adjustable timeframe map backoffice

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#73]
As an employee, I want to be able to open a map view on which all open notifications are visible so that I can see which ones still need to be picked up in my area.

At the moment the map shows the signals of the last 24-hours. Is it possible to make this timeframe adjustable?

**Comment by erikveerm** [comment]
First realization of a dropdown menu with the option to show signals of the past month (30 days). Initially not longer back than 30 days. Possibly later (if desired) the option to show notifications over a specific period of time.

**Comment by boris-arkenaar** [comment]
So, two options, last 24 hours and last 30 days? With last 24 hours selected by default.

**Comment by erikveerm** [comment]
Maybe add a third option: last week (7 days)? Is this something we can adjust ourselves or do we need a developer for this? 
For us the default should be 30 days. I think we'll use that timeframe the most.

**Comment by boris-arkenaar** [comment]
First iteration I'd say:

- these three options (24 hours, 7 days, 30 days)
- default selection is 24 hours (backwards compatible)
- no changes can be made

Next iteration I guess it would be very convenient for you to be able to configure the default selection, so you can set it to 30 days by default.

After that we can see if we can make the list of options configurable.
