### ISSUE TITLE
Separate frontend for Afvalstoffendienst

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#74]
- Separate frontend for Afvalstoffendienst (AFV)
- With logo of AFV
- Separate URL
- Only for AFV signals within the AFV service area
- Frontend Den Bosch for all signals within municipality of Den Bosch
![AFV-logo](https://user-images.githubusercontent.com/66015874/92464214-20da7980-f1cd-11ea-8e68-2346bc3453ce.jpg)

**Comment by bartjkdp** [comment]
Created an initial setup at https://afvalstoffen.signalen.s-hertogenbosch.dev/incident/beschrijf
