### ISSUE TITLE
Assign employee to an incident

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#75]
see Signalen/backend#53

Allow an employee to be assigned to an incident, on the detail page.
See which employee an incident is assigned to, on the list page.

Technical details:

- in /manage/incidents overview, add column that can hold the optional django user name from SignalHandlingUser
- add action to allow assigning of django user to a signal
- add filter to enable filtering based on employee name via SignalHandlingUser

**Comment by boris-arkenaar** [comment]
@erikveerm It feels to me like this can be two separate stories.

- One for assigning a user to an incident (and seeing assigned user per incident in incident overview list).
- One for defining routing rules so new incidents will be assigned to assignment groups automatically.

As per the two use cases defined at the top.

I'll start with assigning users to an incident.

**Comment by boris-arkenaar** [comment]
Updated initial messages accordingly. Only filtering has not been implemented for now.
