### ISSUE TITLE
Change a signal's department within subcategory

### ISSUE THREAD

**Issue by boris-arkenaar** [Signalen/frontend#78]
On the detail page of an incident, you should be able to change the department that has been assigned to it through routing. This is a direct link to a department, instead of indirect through the link with a subcategory.
The possible departments that can be assigned are restricted to the departments linked to the subcategory of the incident.

**Comment by CBuiVNG** [comment]
The routing can add a relation between a signal and a department.

This can be overruled by sending:
TODO add json examples

**Comment by boris-arkenaar** [comment]
What if a signal has not been given a direct relation with a department through routing? Should you be able to change/set such a relation, or nothing at all?
@CBuiVNG @erikveerm

**Comment by boris-arkenaar** [comment]
So, I will check for the existence of a `signal_departments` with `relation_type` == `routing`. If that exists I show this relationship and give the ability to change department.
