### ISSUE TITLE
Remove hardcoded reference to afval/asbest-accu in frontend on standard texts page

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/frontend#80]
**Describe the bug**
When editing the default texts, the frontend by default selects the afval/asbest-accu category. This results in an error on instances where this category does not exist:

https://github.com/Amsterdam/signals-frontend/blob/d193eb7580c74caf8f1712d381178ebe741673f5/src/signals/incident-management/containers/DefaultTextsAdmin/components/SelectForm/index.js#L14-L19

**To Reproduce**

1. Use a category 
1. Go to: /manage/standaard/teksten
1. The error "De opgevraagde gegevens konden niet gevonden worden" is shown

**Expected behavior**
The system shows no category by default or retrieves the first subcategory in the list

**Screenshots**

![image](https://user-images.githubusercontent.com/5213690/96263003-cc43ce80-0fc2-11eb-9e30-46166b30b2e4.png)

**Comment by boris-arkenaar** [comment]
I've taken a quick look at it, hoping it would be an easy fix. But redux and especially the form make it overly complicated and haven't been able to fix it yet. Moving on to higher priority story for now.
