### ISSUE TITLE
Sorting by assigned to doesn't work

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#91]
**Describe the bug**
I click on _toegewezen aan_ and the signals aren't being sorted buy assigned to.

**To Reproduce**
1. Go to the tab _Afhandelen_
2. Click on _Toegewezen aan_

**Expected behavior**
All shown signals are sorted by assinged to

**Comment by CBuiVNG** [comment]
Back-end has ordering option added via https://github.com/Signalen/backend/issues/87. Front-end needs some bits
