### ISSUE TITLE
Expand MapSelectGeneric

### ISSUE THREAD

**Issue by boris-arkenaar** [Signalen/frontend#92]
Add the missing functionality to the `MapSelectGeneric` component.

- Custom icons
- Allow multiple types of assets (with each their own icon)
- Legend, explaining the different types/icons
- Internalize the now external [`leaflet-geojson-bbox-layer`](https://github.com/Amsterdam/leaflet-geojson-bbox-layer/tree/master/src)
- Remove the feature flag `useMapSelectGeneric`, remove the component `MapSelect` and always use the component `MapSelectGeneric`

**Comment by JeroenduC** [comment]
At the gemeente Utrecht we currently have the simple 'donut' icons. We would like the icons to give some information to the user. Our wishes:
-Icons in svg format.
-Grouping of sets of icons when zoomed out. Example: 
![image](https://user-images.githubusercontent.com/49227194/115408264-02bc0980-a1f1-11eb-92e6-9bb50a226a91.png)

Please let us know if we need to elaborate on one of the points above.

**Comment by boris-arkenaar** [comment]
We will allow for different icons, one per type of asset, in SVG format indeed.
Clustering of icons will be added as functionality as well.
Do you have any specific wishes for the cluster icon, as I see they have a red and blue border in your example?

**Comment by JeroenduC** [comment]
That's really good to hear!

As for the cluster icon: the two things we find most important are the information of the number of items underneath the clustered icon and how clear it is. So we think the a clear visual number with a nice contrast with the background. 

We haven't done any user research about the border colour of cluster icons, so it's not necessary for us to add it.
